### ISSUE TITLE
Run distributed Deep learning training much slower when Alluxio cache is not big enough.

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10322]
**Alluxio Version:**
2.1.0

**Describe the bug**
The training data's size is about 143GB, the cache size of Alluxio is about 120GB. And I've already run distributed deep learning training with Alluxio before, so the data has been already loaded to Alluxio.

```
# alluxio fs du -h -s /images
File Size     In Alluxio       Path
143.67GB      90.66GB (63%)    /images
```

```
# alluxio fsadmin report capacity
Capacity information for all workers:
    Total Capacity: 120.00GB
        Tier: MEM  Size: 120.00GB
    Used Capacity: 103.34GB
        Tier: MEM  Size: 103.34GB
    Used Percentage: 86%
    Free Percentage: 14%

Worker Name      Last Heartbeat   Storage       MEM
192.168.0.120    0                capacity      30.00GB
                                  used          28.78GB (95%)
192.168.0.119    0                capacity      30.00GB
                                  used          21.15GB (70%)
192.168.0.117    0                capacity      30.00GB
                                  used          26.37GB (87%)
192.168.0.118    0                capacity      30.00GB
                                  used          27.04GB (90%)
```

But when I run distributed deep learning training again, the speed of training data (4 hosts x 8 GPUs=32GPUs)is not better than OSSFS(which has no cache data ).

Current Performance result:
```
019-10-28T11:10:37.609308324Z ----------------------------------------------------------------
2019-10-28T11:10:37.609844725Z 1000	images/sec: 151.4 +/- 1.5 (jitter = 11.3)	6.477
2019-10-28T11:10:37.609860123Z ----------------------------------------------------------------
2019-10-28T11:10:37.609865115Z total images/sec: 4844.95
2019-10-28T11:10:37.609869535Z ----------------------------------------------------------------
```

The performance result of full cache
```
2019-10-22T08:28:58.587049015Z ----------------------------------------------------------------
2019-10-22T08:28:58.590777055Z 1000	images/sec: 236.3 +/- 0.6 (jitter = 5.9)	5.973
2019-10-22T08:28:58.590795375Z ----------------------------------------------------------------
2019-10-22T08:28:58.590800103Z total images/sec: 7560.32
2019-10-22T08:28:58.590803525Z ----------------------------------------------------------------
```

And I also check the worker's log, see such errors:

```
2019-10-28 11:10:37,238 WARN  SleepingTimer - Worker Space Reserver last execution took 295859 ms. Longer than the interval 1000
2019-10-28 11:10:38,185 WARN  AsyncCacheRequestManager - Failed to async cache block 2315255812 from remote worker (/192.168.0.119:29999) on creating the temp block: Failed to allocate 24193441 bytes on any dir, tierAlias MEM, any medium type after 10,000ms to create blockId 2315255812
2019-10-28 11:10:39,252 WARN  SleepingTimer - Worker Space Reserver last execution took 2014 ms. Longer than the interval 1000
2019-10-28 11:12:48,556 INFO  DynamicResourcePool - Resource alluxio.client.block.stream.DefaultBlockWorkerClient@5295c09d is garbage collected.
2019-10-28 11:12:48,556 INFO  BlockWorkerClientPool - Block worker client for GrpcServerAddress{HostName=iZhp3bku0ru8vuxq08lorxZ, SocketAddress=iZhp3bku0ru8vuxq08lorxZ/192.168.0.119:29999} closed.
2019-10-28 11:16:48,556 INFO  DynamicResourcePool - Resource alluxio.client.block.stream.DefaultBlockWorkerClient@2ec56074 is garbage collected.
2019-10-28 11:16:48,556 INFO  BlockWorkerClientPool - Block worker client for GrpcServerAddress{HostName=iZhp3bku0ru8vuxq08lorxZ, SocketAddress=iZhp3bku0ru8vuxq08lorxZ/192.168.0.119:29999} closed.
```

All the logs are put in [diagnose_alluxio_1572265325.tar.gz](https://github.com/Alluxio/alluxio/files/3779619/diagnose_alluxio_1572265325.tar.gz)

The Alluxio configurations I used:
```
    alluxio.user.block.size.bytes.default: 32MB
    fs.oss.endpoint: oss-cn-huhehaote-internal.aliyuncs.com
    # set OSS endpoint
    fs.oss.accessKeyId: {ak-id}
    fs.oss.accessKeySecret: {ak-secret}
    alluxio.master.mount.table.root.ufs: oss://imagenet-huabei5/
    alluxio.user.file.master.client.threads: 64
    alluxio.user.block.master.client.threads: 64
    # alluxio.underfs.oss.socket.timeout: 3000sec
    #alluxio.user.network.read.chunk.size.bytes: 32MB
    alluxio.user.network.reader.chunk.size.bytes: 32MB

worker:
    jvmOptions: " -Xmx12G"

master:
    jvmOptions: " -Xmx6G"

tieredstore:
  levels:
  - alias: MEM
    mediumtype: MEM,SSD
    level: 0
    path: /dev/shm,/var/lib/docker/alluxio-ssd
    type: hostPath
    quota: 10GB,20GB
    high: 0.99
    low: 0.7

fuse:
  image: alluxio/alluxio-fuse
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
I notice the capacity is changed from time to time. 

```
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers:
    Total Capacity: 120.00GB
        Tier: MEM  Size: 120.00GB
    Used Capacity: 108.29GB
        Tier: MEM  Size: 108.29GB
    Used Percentage: 90%
    Free Percentage: 10%

Worker Name      Last Heartbeat   Storage       MEM
192.168.0.120    0                capacity      30.00GB
                                  used          29.03GB (96%)
192.168.0.119    0                capacity      30.00GB
                                  used          28.89GB (96%)
192.168.0.117    0                capacity      30.00GB
                                  used          29.23GB (97%)
192.168.0.118    0                capacity      30.00GB
                                  used          21.14GB (70%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers:
    Total Capacity: 120.00GB
        Tier: MEM  Size: 120.00GB
    Used Capacity: 92.91GB
        Tier: MEM  Size: 92.91GB
    Used Percentage: 77%
    Free Percentage: 23%

Worker Name      Last Heartbeat   Storage       MEM
192.168.0.120    0                capacity      30.00GB
                                  used          21.07GB (70%)
192.168.0.119    0                capacity      30.00GB
                                  used          25.75GB (85%)
192.168.0.117    0                capacity      30.00GB
                                  used          24.29GB (80%)
192.168.0.118    0                capacity      30.00GB
                                  used          21.80GB (72%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers:
    Total Capacity: 120.00GB
        Tier: MEM  Size: 120.00GB
    Used Capacity: 107.49GB
        Tier: MEM  Size: 107.49GB
    Used Percentage: 89%
    Free Percentage: 11%

Worker Name      Last Heartbeat   Storage       MEM
192.168.0.120    0                capacity      30.00GB
                                  used          25.49GB (84%)
192.168.0.119    0                capacity      30.00GB
                                  used          27.24GB (90%)
192.168.0.117    0                capacity      30.00GB
                                  used          27.85GB (92%)
192.168.0.118    0                capacity      30.00GB
                                  used          26.91GB (89%)
```

**Comment by cheyang** [comment]
And the properties:

```
properties:
  alluxio.fuse.debug.enabled: "false"
  alluxio.master.journal.folder: /journal
  alluxio.master.journal.type: UFS
  alluxio.master.mount.table.root.ufs: oss://imagenet-huabei5/
  alluxio.security.stale.channel.purge.interval: 365d
  alluxio.underfs.oss.streaming.download.enabled: "false"
  alluxio.underfs.oss.streaming.download.partition.size: 16MB
  alluxio.underfs.oss.streaming.download.task.num: "8"
  alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 2GB
  alluxio.user.block.master.client.threads: 64
  alluxio.user.block.size.bytes.default: 32MB
  alluxio.user.block.write.location.policy.class: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
  alluxio.user.file.master.client.threads: 64
  alluxio.user.file.passive.cache.enabled: false
  alluxio.user.file.writetype.default: MUST_CACHE
  alluxio.user.network.reader.chunk.size.bytes: 32MB
  alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
  alluxio.worker.allocator.class: alluxio.worker.block.allocator.GreedyAllocator
```
