### ISSUE TITLE
Run distributed Deep learning training when data is pinned much slower than expected when Alluxio cache is not big enough.

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10401]
**Alluxio Version:**

alluxio version -r
2.1.0-SNAPSHOT-ec12adc44298d5887697b517177d1b86963e7662

**Describe the bug**

1. The training data's size is about 143GB, the cache size of Alluxio is about 120GB. And I've already run distributed deep learning training with Alluxio before, so the data has been already loaded to Alluxio.

```
bash-4.4# alluxio fs du -sh /images
File Size     In Alluxio       Path
143.67GB      119.84GB (83%)   /images
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers:
    Total Capacity: 120.00GB
        Tier: MEM  Size: 120.00GB
    Used Capacity: 119.99GB
        Tier: MEM  Size: 119.99GB
    Used Percentage: 99%
    Free Percentage: 1%

Worker Name      Last Heartbeat   Storage       MEM
192.168.0.195    0                capacity      30.00GB
                                  used          30.00GB (99%)
192.168.0.117    0                capacity      30.00GB
                                  used          30.00GB (99%)
192.168.0.118    0                capacity      30.00GB
                                  used          30.00GB (99%)
192.168.0.194    0                capacity      30.00GB
                                  used          30.00GB (99%)
```

2. Pin the directory `/images`

```
alluxio fs stat /images
/images is a directory path.
FileInfo{fileId=1, name=images, path=/images, ufsPath=oss://imagenet-huabei5/images, length=1152, blockSizeBytes=0, creationTimeMs=1572617375494, completed=true, folder=true, pinned=true, pinnedlocation=[], cacheable=false, persisted=true, blockIds=[], inMemoryPercentage=0, lastModificationTimesMs=1572671533042, ttl=-1, lastAccessTimesMs=1572617375482, ttlAction=DELETE, owner=, group=, mode=511, persistenceState=PERSISTED, mountPoint=false, replicationMax=0, replicationMin=0, fileBlockInfos=[], mountId=1, inAlluxioPercentage=0, ufsFingerprint=, acl=user::rwx,group::rwx,other::rwx, defaultAcl=}
```

3. But when I run distributed deep learning training again, the speed of training data (4 hosts x 8 GPUs=32GPUs)is even much worse than OSSFS(which has no cache data ).

Current Performance result:

```
----------------------------------------------------------------
1000	images/sec: 59.4 +/- 2.8 (jitter = 14.3)	6.345
----------------------------------------------------------------
total images/sec: 1901.84
----------------------------------------------------------------
```

The performance result of full cache

```
2019-10-22T08:28:58.587049015Z ----------------------------------------------------------------
2019-10-22T08:28:58.590777055Z 1000	images/sec: 236.3 +/- 0.6 (jitter = 5.9)	5.973
2019-10-22T08:28:58.590795375Z ----------------------------------------------------------------
2019-10-22T08:28:58.590800103Z total images/sec: 7560.32
2019-10-22T08:28:58.590803525Z --------------------------------------------------
```

Even ossfs's performance is about 160 images/second per GPU, and total speed is 3500 images/second in total

4. The properties I set

```
properties:
    alluxio.user.file.passive.cache.enabled: false
    alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 2GB
    alluxio.user.file.writetype.default: MUST_CACHE
    alluxio.worker.allocator.class: alluxio.worker.block.allocator.RoundRobinAllocator
    alluxio.user.block.size.bytes.default: 32MB
    fs.oss.endpoint: oss-cn-huhehaote-internal.aliyuncs.com
    # set OSS endpoint
    alluxio.user.file.master.client.threads: 64
    alluxio.user.block.master.client.threads: 64
    # alluxio.underfs.oss.socket.timeout: 3000sec
    #alluxio.user.network.read.chunk.size.bytes: 32MB
    alluxio.user.network.reader.chunk.size.bytes: 32MB

worker:
    jvmOptions: " -Xmx12G"

master:
    jvmOptions: " -Xmx6G"

tieredstore:
  levels:
  - alias: MEM
    mediumtype: MEM,SSD
    level: 0
    path: /dev/shm,/var/lib/docker/alluxio-ssd
    type: hostPath
    quota: 10GB,20GB
    high: 0.99
    low: 0.7
```

5. When I checked the logs:

```
2019-11-02 06:26:31,548 WARN  UnderFileSystemBlockReader - Failed to cache data read from UFS (on transferTo()): Failed to request 90348 bytes after 10,000ms to create blockId 1140850689
2019-11-02 06:26:32,490 WARN  SpaceReserver - SpaceReserver failed to free 9663676416 bytes on tier MEM for high watermarks: Failed to find an eviction plan to free 9663676416 bytes space at location MEM
2019-11-02 06:26:33,491 WARN  SpaceReserver - SpaceReserver failed to free 9663676416 bytes on tier MEM for high watermarks: Failed to find an eviction plan to free 9663676416 bytes space at location MEM
2019-11-02 06:26:34,492 WARN  SpaceReserver - SpaceReserver failed to free 9663676416 bytes on tier MEM for high watermarks: Failed to find an eviction plan to free 9663676416 bytes space at location MEM
```

6. The whole logs are here

[diagnose_alluxio_1572675997.tar.gz](https://github.com/Alluxio/alluxio/files/3800247/diagnose_alluxio_1572675997.tar.gz)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
Is it possible to disable eviction? I tried to set `alluxio.worker.tieredstore.level0.watermark.high.ratio=2`, but  it doesn't help. I want to check if it's due to eviction behavior.

```
2019-11-02 08:01:29,729 ERROR ProcessUtils - Uncaught exception while running Alluxio worker @192.168.0.117:29999, stopping it and exiting. Exception "java.lang.IllegalArgumentException: The high watermark of tier 0 should be less than 1.0, but is 2.0", Root Cause "null"
java.lang.IllegalArgumentException: The high watermark of tier 0 should be less than 1.0, but is 2.0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
	at alluxio.worker.block.SpaceReserver.updateStorageInfo(SpaceReserver.java:84)
	at alluxio.worker.block.SpaceReserver.<init>(SpaceReserver.java:65)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:223)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:77)
	at alluxio.Registry.start(Registry.java:131)
	at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:283)
	at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:235)
	at alluxio.ProcessUtils.run(ProcessUtils.java:35)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:71)
```

**Comment by cheyang** [comment]
I'm able to set `alluxio.worker.tieredstore.level0.watermark.high.ratio=2`, but it doesn't help. The performance is not improved.

I suspect the performance downgrade is from 

```
2019-11-02 06:15:31,941 WARN  UnderFileSystemBlockReader - Failed to cache data read from UFS (on transferTo()): Failed to request 55480 bytes after 10,000ms to create blockId 5838471168
2019-11-02 06:15:32,030 WARN  AsyncCacheRequestManager - Failed to async cache block 13170114560 from remote worker (/192.168.0.194:29999) on creating the temp block: Failed to allocate 33554432 bytes on any dir, tierAlias MEM, any medium type after 10,000ms to create blockId 13170114560

```

**Comment by cheyang** [comment]
In order to simplify the test scenario,  we change that the memory layer only has `/dev/shm`.  And other configurations are the same as  [above](https://github.com/Alluxio/alluxio/issues/10401#issuecomment-549053297). And use `alluxio.worker.tieredstore.level0.watermark.high.ratio=2` to avoid eviction.

1. The properties are as below:
```
properties:
  alluxio.master.mount.table.root.ufs: oss://imagenet-huabei5/
  alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 2GB
  alluxio.user.block.master.client.threads: 64
  alluxio.user.block.size.bytes.default: 32MB
  alluxio.user.file.master.client.threads: 64
  alluxio.user.file.passive.cache.enabled: false
  alluxio.user.file.writetype.default: MUST_CACHE
  alluxio.user.network.reader.chunk.size.bytes: 32MB
  alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstPolicy
  alluxio.worker.allocator.class: alluxio.worker.block.allocator.RoundRobinAllocator
  alluxio.worker.file.buffer.size: 64MB
tieredstore:
  levels:
  - alias: MEM
    high: 2
    level: 0
    low: 0.9
    path: /dev/shm
    quota: 30GB
    type: hostPath
```
2. Pin the directory `/images`

```
alluxio fs pin /images
```

3. The performance is decreased when the alluxio cache is full

```
170	images/sec: 191.7 +/- 2.5 (jitter = 36.8)	7.467
170	images/sec: 191.7 +/- 2.5 (jitter = 36.8)	7.299

450	images/sec: 91.8 +/- 3.0 (jitter = 40.1)	5.701
450	images/sec: 91.8 +/- 3.0 (jitter = 40.5)	5.487


650	images/sec: 75.5 +/- 2.9 (jitter = 35.2)	5.455
650	images/sec: 75.5 +/- 2.9 (jitter = 33.1)	5.776

950	images/sec: 63.8 +/- 2.7 (jitter = 31.4)	6.305
950	images/sec: 63.8 +/- 2.7 (jitter = 31.4)	5.919

990	images/sec: 62.4 +/- 2.6 (jitter = 29.9)	5.866
1000	images/sec: 62.8 +/- 2.6 (jitter = 29.8)	6.225
```

4. And I have seen a lot of the warning:

```
2019-11-03 07:10:25,040 WARN  UnderFileSystemBlockReader - Failed to update block writer for UFS block [blockId: 12415139843, ufsPath: oss://imagenet-huabei5/images/train-00739-of-01024, offset: 0]: Failed to allocate 67108864 bytes on any dir, tierAlias MEM, any medium type after 10,000ms to create blockId 12415139843
```

5. All the logs are attached:

[diagnose_alluxio_1572782178.tar.gz](https://github.com/Alluxio/alluxio/files/3801547/diagnose_alluxio_1572782178.tar.gz)
