### ISSUE TITLE
在fuse下测试读写速率，结果很不理想，是不是我配置有问题

### ISSUE THREAD

**Issue by we7team** [Alluxio/alluxio#10517]
**Alluxio Version:**
alluxio/alluxio-fuse:2.1.0

**Describe the bug**
我是直接使用helm工具生成的helm包直接部署的。
一个节点服务器的集群环境，一个master，一个woker，一个fuse。

### BUG1：
在fuse挂载的目录下测试读写速率，结果很低
**首次写：**
![image](https://user-images.githubusercontent.com/4837122/69669593-20a13f80-10cd-11ea-9645-404331f4b599.png)
**首次读：**
![image](https://user-images.githubusercontent.com/4837122/69669637-31ea4c00-10cd-11ea-99df-b2590106cde8.png)
**多次读：**
![image](https://user-images.githubusercontent.com/4837122/69669680-4a5a6680-10cd-11ea-8591-0676b52c7769.png)

**而我在/dev/shm下的测试结果：**
![image](https://user-images.githubusercontent.com/4837122/69669762-74ac2400-10cd-11ea-905c-916b051d92d0.png)

对比可以看出通过alluxio进行读写，没有达到内存级别的效果，对比结果差距很大。
测试写：`time dd if=/dev/zero of=testfile bs=8k count=1024`
测试读：`time dd if=testfile of=/dev/null bs=8k count=1024`

**WEB端页面（可以看到我这8M的文件确实是存内存里了）：**
![image](https://user-images.githubusercontent.com/4837122/69671439-023d4300-10d1-11ea-967a-9142bc2d9774.png)
![image](https://user-images.githubusercontent.com/4837122/69672048-40873200-10d2-11ea-9012-a547747a4b51.png)

贴一下我集群的配置信息：
**master yaml（注意：隐藏了NFS挂载信息）：**
```
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: alluxio
    chart: alluxio-2.1.0
    heritage: Tiller
    name: alluxio-master-0
    release: alluxio
    role: alluxio-master
  name: alluxio-master-0
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alluxio
      name: alluxio-master-0
      role: alluxio-master
  serviceName: master-0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alluxio
        chart: alluxio-2.1.0
        heritage: Tiller
        name: alluxio-master-0
        release: alluxio
        role: alluxio-master
    spec:
      containers:
      - args:
        - master-only
        - --no-format
        command:
        - /entrypoint.sh
        envFrom:
        - configMapRef:
            name: alluxio-config
        image: alluxio/alluxio:2.1.0
        imagePullPolicy: IfNotPresent
        name: alluxio-master
        ports:
        - containerPort: 19998
          name: rpc
          protocol: TCP
        - containerPort: 19999
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: "1"
            memory: 1G
        securityContext:
          procMount: Default
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /journal
          name: alluxio-journal
        - mountPath: /mnt/nfs-attachment
          name: nfs-attachment
      - args:
        - job-master
        command:
        - /entrypoint.sh
        envFrom:
        - configMapRef:
            name: alluxio-config
        image: alluxio/alluxio:2.1.0
        imagePullPolicy: IfNotPresent
        name: alluxio-job-master
        ports:
        - containerPort: 20001
          name: job-rpc
          protocol: TCP
        - containerPort: 20002
          name: job-web
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: "1"
            memory: 1G
        securityContext:
          procMount: Default
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/nfs-attachment
          name: nfs-attachment
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/chown
        - -R
        - 1000:1000
        - /journal
        image: alluxio/alluxio:2.1.0
        imagePullPolicy: IfNotPresent
        name: journal-chown
        resources: {}
        securityContext:
          procMount: Default
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /journal
          name: alluxio-journal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: alluxio-journal
        persistentVolumeClaim:
          claimName: alluxio-pv-claim
      - name: nfs-attachment
        nfs:
          path: /www/attachment
          server: 10.0.64.xx
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```

**worker yaml（注意：隐藏了NFS挂载信息）：**
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: alluxio
    chart: alluxio-2.1.0
    heritage: Tiller
    release: alluxio
    role: alluxio-worker
  name: alluxio-worker
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alluxio
      release: alluxio
      role: alluxio-worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alluxio
        chart: alluxio-2.1.0
        heritage: Tiller
        release: alluxio
        role: alluxio-worker
    spec:
      containers:
      - args:
        - worker-only
        - --no-format
        command:
        - /entrypoint.sh
        env:
        - name: ALLUXIO_WORKER_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        envFrom:
        - configMapRef:
            name: alluxio-config
        image: alluxio/alluxio:2.1.0
        imagePullPolicy: IfNotPresent
        name: alluxio-worker
        ports:
        - containerPort: 29999
          hostPort: 29999
          name: rpc
          protocol: TCP
        - containerPort: 30000
          hostPort: 30000
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2G
          requests:
            cpu: "1"
            memory: 2G
        securityContext:
          procMount: Default
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/domain
          name: alluxio-domain
        - mountPath: /mnt/alluxio-hdd-cache
          name: hdd-cache
        - mountPath: /dev/shm
          name: mem-cache
        - mountPath: /mnt/nfs-attachment
          name: nfs-attachment
      - args:
        - job-worker
        command:
        - /entrypoint.sh
        env:
        - name: ALLUXIO_WORKER_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        envFrom:
        - configMapRef:
            name: alluxio-config
        image: alluxio/alluxio:2.1.0
        imagePullPolicy: IfNotPresent
        name: alluxio-job-worker
        ports:
        - containerPort: 30001
          hostPort: 30001
          name: job-rpc
          protocol: TCP
        - containerPort: 30002
          hostPort: 30002
          name: job-data
          protocol: TCP
        - containerPort: 30003
          hostPort: 30003
          name: job-web
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: "1"
            memory: 1G
        securityContext:
          procMount: Default
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/domain
          name: alluxio-domain
        - mountPath: /mnt/alluxio-hdd-cache
          name: hdd-cache
        - mountPath: /dev/shm
          name: mem-cache
        - mountPath: /mnt/nfs-attachment
          name: nfs-attachment
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
      - command:
        - /bin/chown
        - -R
        - 1000:1000
        - /opt/domain
        - /mnt/alluxio-hdd-cache
        - /dev/shm
        image: alluxio/alluxio:2.1.0
        imagePullPolicy: IfNotPresent
        name: socket-chown
        resources: {}
        securityContext:
          procMount: Default
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/domain
          name: alluxio-domain
        - mountPath: /mnt/alluxio-hdd-cache
          name: hdd-cache
        - mountPath: /dev/shm
          name: mem-cache
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /tmp/alluxio-domain
          type: DirectoryOrCreate
        name: alluxio-domain
      - hostPath:
          path: /mnt/alluxio-hdd-cache
          type: DirectoryOrCreate
        name: hdd-cache
      - emptyDir:
          medium: Memory
          sizeLimit: 2G
        name: mem-cache
      - name: nfs-attachment
        nfs:
          path: /www/attachment
          server: 10.0.64.xx
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

**fuse yaml：**
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: alluxio
    chart: alluxio-2.1.0
    heritage: Tiller
    release: alluxio
    role: alluxio-fuse
  name: alluxio-fuse
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alluxio
      chart: alluxio-2.1.0
      heritage: Tiller
      release: alluxio
      role: alluxio-fuse
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alluxio
        chart: alluxio-2.1.0
        heritage: Tiller
        release: alluxio
        role: alluxio-fuse
    spec:
      affinity:
        podAffinity: {}
      containers:
      - args:
        - fuse
        - --fuse-opts=allow_other,uid=1000,gid=1000
        command:
        - /entrypoint.sh
        env:
        - name: ALLUXIO_CLIENT_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ALLUXIO_CLIENT_JAVA_OPTS
          value: '-Dalluxio.user.hostname=$(ALLUXIO_CLIENT_HOSTNAME) '
        - name: ALLUXIO_JAVA_OPTS
          value: '-Dalluxio.master.hostname=alluxio-master-0 -Dalluxio.user.file.metadata.load.type=ONCE '
        image: alluxio/alluxio-fuse:2.1.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/alluxio/integration/fuse/bin/alluxio-fuse
              - unmount
              - /alluxio-fuse
        name: alluxio-fuse
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/fuse
          name: alluxio-fuse-device
        - mountPath: /alluxio-fuse
          mountPropagation: Bidirectional
          name: alluxio-fuse-mount
        - mountPath: /opt/domain
          name: alluxio-domain
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev/fuse
          type: File
        name: alluxio-fuse-device
      - hostPath:
          path: /alluxio-fuse
          type: DirectoryOrCreate
        name: alluxio-fuse-mount
      - hostPath:
          path: /tmp/alluxio-domain
          type: Directory
        name: alluxio-domain
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

**alluxio-config 配置文件（注意：隐藏了ufs配置信息）：**
```
apiVersion: v1
data:
  ALLUXIO_FUSE_JAVA_OPTS: '-Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME} -Dalluxio.worker.hostname=${ALLUXIO_CLIENT_HOSTNAME}  -XX:MaxDirectMemorySize=2g '
  ALLUXIO_JAVA_OPTS: '-Dalluxio.master.hostname=alluxio-master-0 -Dalluxio.master.journal.type=UFS
    -Dalluxio.master.journal.folder=/journal -Dalluxio.security.stale.channel.purge.interval=365d
    -Dalluxio.security.authorization.permission.enabled=false -Dalluxio.master.security.impersonation.alluxio.users=*
    -Dalluxio.master.security.impersonation.alluxio.groups=* -Dalluxio.master.periodic.block.integrity.check.repair=true
    -Dalluxio.master.mount.table.root.ufs=cos://alluxio/ -Dfs.cos.access.key=xxx
    -Dfs.cos.secret.key=xxx -Dfs.cos.region=ap-shanghai
    -Dfs.cos.app.id=xxx -Dalluxio.worker.data.server.domain.socket.address=/opt/domain
    -Dalluxio.worker.data.server.domain.socket.as.uuid=true -Dalluxio.worker.tieredstore.levels=2
    -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=MEM -Dalluxio.worker.tieredstore.level0.dirs.path=/dev/shm
    -Dalluxio.worker.tieredstore.level0.dirs.quota=2G -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95
    -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7 -Dalluxio.worker.tieredstore.level1.alias=HDD
    -Dalluxio.worker.tieredstore.level1.dirs.path=/mnt/alluxio-hdd-cache -Dalluxio.worker.tieredstore.level1.dirs.quota=20GB
    -Dalluxio.worker.tieredstore.level1.watermark.high.ratio=0.9 -Dalluxio.worker.tieredstore.level1.watermark.low.ratio=0.7 '
  ALLUXIO_JOB_MASTER_JAVA_OPTS: '-Dalluxio.job.master.bind.host=0.0.0.0 '
  ALLUXIO_JOB_WORKER_JAVA_OPTS: '-Dalluxio.job.worker.rpc.port=30001  -Dalluxio.job.worker.data.port=30002
    -Dalluxio.job.worker.web.port=30003 -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME}  '
  ALLUXIO_MASTER_JAVA_OPTS: '-Dalluxio.master.web.bind.host=0.0.0.0 '
  ALLUXIO_WORKER_JAVA_OPTS: '-Dalluxio.worker.bind.host=0.0.0.0 -Dalluxio.worker.rpc.port=29999
    -Dalluxio.worker.web.port=30000 -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} '
  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: /dev/shm
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: alluxio
    chart: alluxio-2.1.0
    heritage: Tiller
    name: alluxio-config
    release: alluxio
  name: alluxio-config
  namespace: default

```

### BUG2：
另外还有一个问题，我们今天做压测时，fuse和master都比较不稳定，压测逻辑是循环创建1000个内容为“123”的文件，结果还没写完就挂了。
