### ISSUE TITLE
fuse与nfs结合后，写入的文件都是空文件

### ISSUE THREAD

**Issue by we7team** [Alluxio/alluxio#10554]
**Alluxio Version:**
alluxio/alluxio-fuse:2.2.0-SNAPSHOT

**Describe the bug**
之前发现fuse在k8s环境中，使用`mountPropagation: Bidirectional`挂载会导致非正常重启无法umount的问题，我认为在fuse上加一层nfs，用nfs可以完美解决这个问题。具体看：https://github.com/Alluxio/alluxio/issues/10533

但是我在实践中发现，从nfs客户端往fuse里写入的都是空文件
![image](https://user-images.githubusercontent.com/4837122/70068686-6d37ce00-162b-11ea-9e00-07acb222d8a6.png)

猜测可能是因为nfs的写入方式，是先创建文件，再写入内容数据，由于alluxio只能写一次，导致内容数据没写进去。

基于fuse兼容k8s存储成本比较高，使用nfs成本比较低，提出这个问题，讨论一下，看看有没有解决方案。

**dockerfile：**
```
FROM alluxio/alluxio-fuse:2.2.0-SNAPSHOT AS alluxio-extractor
FROM itsthenetwork/nfs-server-alpine:latest AS nfs-extractor
FROM adoptopenjdk/openjdk8:x86_64-alpine-jdk8u-nightly-slim
RUN set -ex \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
    && apk update \
    && apk upgrade \
    && apk add --no-cache shadow fuse-dev

# alluxio-fuse
ARG ALLUXIO_USERNAME=alluxio
ARG ALLUXIO_GROUP=alluxio
ARG ALLUXIO_UID=1000
ARG ALLUXIO_GID=1000

# if Alluxio user, group, gid, and uid aren't root|0
# then create the alluxio user and set file permissions accordingly
RUN if [ ${ALLUXIO_USERNAME} != "root" ] \
    && [ ${ALLUXIO_GROUP} != "root" ] \
    && [ ${ALLUXIO_UID} -ne 0 ] \
    && [ ${ALLUXIO_GID} -ne 0 ]; then \
      addgroup -g ${ALLUXIO_GID} ${ALLUXIO_GROUP} && \
      adduser --system -u ${ALLUXIO_UID} -g ${ALLUXIO_GID} ${ALLUXIO_USERNAME} && \
      usermod -a -G root ${ALLUXIO_USERNAME} && \
      mkdir -p /journal && \
      chown -R ${ALLUXIO_UID}:${ALLUXIO_GID} /journal && \
      chmod -R g=u /journal && \
      mkdir /alluxio-fuse && \
      chown -R ${ALLUXIO_UID}:${ALLUXIO_GID} /alluxio-fuse; \
    fi

COPY --from=alluxio-extractor /opt/alluxio/integration/fuse  /opt/alluxio/integration/fuse
COPY --from=alluxio-extractor /opt/alluxio/conf  /opt/alluxio/conf
COPY --from=alluxio-extractor /opt/alluxio/libexec /opt/alluxio/libexec
COPY --from=alluxio-extractor /entrypoint.sh /

RUN chown -R ${ALLUXIO_USERNAME}:${ALLUXIO_GROUP} /opt/ /entrypoint.sh

# nfs-server
RUN apk add --no-cache --update --verbose nfs-utils iproute2 && \
    rm -rf /var/cache/apk /tmp /sbin/halt /sbin/poweroff /sbin/reboot && \
    mkdir -p /var/lib/nfs/rpc_pipefs /var/lib/nfs/v4recovery && \
    echo "rpc_pipefs    /var/lib/nfs/rpc_pipefs rpc_pipefs      defaults        0       0" >> /etc/fstab && \
    echo "nfsd  /proc/fs/nfsd   nfsd    defaults        0       0" >> /etc/fstab

COPY --from=nfs-extractor /etc/exports /etc/
COPY --from=nfs-extractor /usr/bin/nfsd.sh /
COPY --from=nfs-extractor /root/.bashrc /root/

RUN chmod +x /nfsd.sh

# end
RUN apk add --no-cache --update bash bash-doc bash-completion \
    && cd /bin && rm -f sh && ln -s /bin/bash sh \
    && rm -rf /var/cache/apk/* /tmp/*

USER ${ALLUXIO_UID}
ENTRYPOINT ["/entrypoint.sh"]
```

**fuse yaml：**
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: alluxio
    chart: alluxio-2.1.0
    heritage: Tiller
    release: alluxio
    role: alluxio-fuse
  name: alluxio-fuse
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alluxio
      chart: alluxio-2.1.0
      heritage: Tiller
      release: alluxio
      role: alluxio-fuse
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alluxio
        chart: alluxio-2.1.0
        heritage: Tiller
        release: alluxio
        role: alluxio-fuse
    spec:
      affinity:
        podAffinity: {}
      containers:
      - args:
        - (/entrypoint.sh fuse --fuse-opts=allow_other)& sleep 3 && /nfsd.sh
        command:
        - /bin/sh
        - -c
        - --
        env:
        - name: SHARED_DIRECTORY
          value: /alluxio-fuse
        - name: SYNC
          value: "true"
        - name: ALLUXIO_CLIENT_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ALLUXIO_CLIENT_JAVA_OPTS
          value: '-Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME} -Dalluxio.worker.hostname=${ALLUXIO_CLIENT_HOSTNAME}  -XX:MaxDirectMemorySize=2g '
        - name: ALLUXIO_JAVA_OPTS
          value: '-Dalluxio.master.hostname=alluxio-master-0 -Dalluxio.user.file.metadata.load.type=ONCE
            -Dalluxio.fuse.user.group.translation.enabled=true '
        image: xxx/alluxio:alluxio-fuse
        imagePullPolicy: Always
        name: alluxio-fuse
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/fuse
          name: alluxio-fuse-device
        - mountPath: /opt/domain
          name: alluxio-domain
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev/fuse
          type: File
        name: alluxio-fuse-device
      - hostPath:
          path: /tmp/alluxio-domain
          type: Directory
        name: alluxio-domain
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

```
