### ISSUE TITLE
Failed to read the data from cache system  due to execution pool is full

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10681]
**Alluxio Version:**
2.1.1-cdb3e7a170edbcfdace15e41eb40b57b8899cb33

**Describe the bug**
I enabled metadata cache

```
alluxio.user.metadata.cache.enabled: "true"
alluxio.user.metadata.cache.max.size: "1000000"
```

And found the error in fuse log:
```
alluxio-fuse-hqr7k-alluxio-fuse.log:2019-12-27 16:53:26,298 ERROR AlluxioFuseFileSystem - Failed to open file /train-00726-of-01024
alluxio-fuse-hqr7k-alluxio-fuse.log-java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@549158ae rejected from java.util.concurrent.ThreadPoolExecutor@4c3c68a8[Running, pool size = 123, active threads = 123, queued tasks = 0, completed tasks = 4494]
alluxio-fuse-hqr7k-alluxio-fuse.log-	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at alluxio.client.file.CachingFileSystem.asyncUpdateFileAccessTime(CachingFileSystem.java:104)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at alluxio.client.file.CachingFileSystem.getStatus(CachingFileSystem.java:81)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:415)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:406)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at alluxio.fuse.AlluxioFuseFileSystem.open(AlluxioFuseFileSystem.java:517)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$2(AbstractFuseFS.java:131)
alluxio-fuse-hqr7k-alluxio-fuse.log-	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$8.invoke(Unknown Source)
alluxio-fuse-hqr7k-alluxio-fuse.log-2019-12-27 16:53:26,298 ERROR AlluxioFuseFileSystem - Failed to get info of /train-00347-of-01024
```

**To Reproduce**
1. Deploy alluxio in kubernetes, the value file is 
```
image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio
imageTag: "2.1.1"
imagePullPolicy: Always

properties:
    alluxio.user.file.passive.cache.enabled: false
    alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    # It should be great than (120)*0.01 = 2GB
    alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 2GB
    alluxio.fuse.debug.enabled: "false"
    alluxio.user.file.writetype.default: MUST_CACHE
    alluxio.user.block.write.location.policy.class: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    alluxio.worker.allocator.class: alluxio.worker.block.allocator.GreedyAllocator
    alluxio.user.block.size.bytes.default: 32MB
    fs.oss.endpoint: oss-cn-shanghai-internal.aliyuncs.com
    # set OSS endpoint
    fs.oss.accessKeyId: xxx
    fs.oss.accessKeySecret: yyy
    alluxio.master.mount.table.root.ufs: oss://imagenet-shanghai/
    alluxio.user.file.master.client.threads: "128"
    alluxio.user.block.master.client.threads: "128"
    # alluxio.underfs.oss.socket.timeout: 3000sec
    alluxio.user.network.reader.chunk.size.bytes: 32MB
    alluxio.worker.file.buffer.size: 64MB
    alluxio.security.stale.channel.purge.interval: 365d
    alluxio.user.metadata.cache.enabled: "true"
    alluxio.user.metadata.cache.max.size: "1000000"
    alluxio.user.direct.memory.io.enabled: "true"
    alluxio.fuse.cached.paths.max: "1000000"
    alluxio.job.worker.threadpool.size: "64"
    alluxio.worker.block.master.client.pool.size: 128

worker:
    jvmOptions: " -Xmx12G"

master:
    jvmOptions: " -Xmx6G"

tieredstore:
  levels:
  - alias: MEM
    level: 0
    path: /dev/shm
    type: hostPath
    # quota: 120GB
    high: 0.99
    low: 0.7

fuse:
  image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio-fuse
  imageTag: "2.1.1"
  imagePullPolicy: Always
  # Customize the MaxDirectMemorySize
  jvmOptions: " -Xmx16G -Xms16G -XX:+UseG1GC -XX:MaxDirectMemorySize=16g "
  shortCircuitPolicy: local
  args:
    - fuse
    - --fuse-opts=direct_io
```

And run TensorFlow training,  the training is failed. And I found the error above in alluxio-fuse logs. The logs are 

[diagnose_alluxio_1577465683.tar.gz](https://github.com/Alluxio/alluxio/files/4005868/diagnose_alluxio_1577465683.tar.gz)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
