### ISSUE TITLE
Performance Overhead using read type as CACHE_PROMOTE v.s NO_CACHE

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10688]
**Alluxio Version:**
2.1.1

**Describe the bug**

Deploy alluxio in kubernetes with CACHE_PROMOTE and NO_CACHE, and I found the NO_CAHCE performance is much better than CACHE_PROMOTE. The file is about 130MB, and 1154 files in all. 

**To Reproduce**
1. Deploy Alluxio with helm chart, the values file uses NO_CACHE

```
image: alluxio/alluxio
imageTag: "2.1.1"
imagePullPolicy: Always

properties:
    alluxio.user.metrics.collection.enabled: false
    alluxio.user.file.passive.cache.enabled: false
    alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    # It should be great than (120)*0.01 = 2GB
    alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 2GB
    alluxio.fuse.debug.enabled: "false"
    alluxio.user.file.writetype.default: MUST_CACHE
    alluxio.user.block.write.location.policy.class: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    alluxio.worker.allocator.class: alluxio.worker.block.allocator.GreedyAllocator
    alluxio.user.block.size.bytes.default: 32MB
    fs.oss.endpoint: oss-cn-shanghai-internal.aliyuncs.com
    # set OSS endpoint
    fs.oss.accessKeyId: xxx
    fs.oss.accessKeySecret: yyy
    alluxio.user.file.readtype.default: NO_CACHE
    alluxio.master.mount.table.root.ufs: oss://imagenet/
    #alluxio.user.file.master.client.threads: "128"
    #alluxio.user.block.master.client.threads: "128"
    # alluxio.underfs.oss.socket.timeout: 3000sec
    alluxio.user.network.reader.chunk.size.bytes: 32MB
    alluxio.worker.file.buffer.size: 320MB
    alluxio.security.stale.channel.purge.interval: 365d
    alluxio.user.metadata.cache.enabled: "false"
    alluxio.user.metadata.cache.max.size: "1000000"
    alluxio.user.direct.memory.io.enabled: "true"
    alluxio.fuse.cached.paths.max: "1000000"
    alluxio.job.worker.threadpool.size: "64"
    alluxio.worker.block.master.client.pool.size: 128


tieredstore:
  levels:
  - alias: MEM
    level: 0
    path: /dev/shm
    type: hostPath
    # quota: 120GB
    high: 0.99
    low: 0.7

fuse:
  image: alluxio/alluxio-fuse
  imageTag: "2.1.1"
  imagePullPolicy: Always
  args:
    - fuse
    - --fuse-opts=direct_io
```

2. Run the training jobs without any cache
3. Performance result is :

```
10000	images/sec: 897.3 +/- 2.1 (jitter = 37.6)	4.466
----------------------------------------------------------------
total images/sec: 7171.94
----------------------------------------------------------------
```

4. Deploy the alluxio without setting alluxio.user.file.readtype.default

```
image: alluxio/alluxio
imageTag: "2.1.1"
imagePullPolicy: Always

properties:
    alluxio.user.metrics.collection.enabled: false
    alluxio.user.file.passive.cache.enabled: false
    alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    # It should be great than (120)*0.01 = 2GB
    alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 2GB
    alluxio.fuse.debug.enabled: "false"
    alluxio.user.file.writetype.default: MUST_CACHE
    alluxio.user.block.write.location.policy.class: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    alluxio.worker.allocator.class: alluxio.worker.block.allocator.GreedyAllocator
    alluxio.user.block.size.bytes.default: 32MB
    fs.oss.endpoint: oss-cn-shanghai-internal.aliyuncs.com
    # set OSS endpoint
    fs.oss.accessKeyId: xxx
    fs.oss.accessKeySecret: yyy
    alluxio.master.mount.table.root.ufs: oss://imagenet/
    #alluxio.user.file.master.client.threads: "128"
    #alluxio.user.block.master.client.threads: "128"
    # alluxio.underfs.oss.socket.timeout: 3000sec
    alluxio.user.network.reader.chunk.size.bytes: 32MB
    alluxio.worker.file.buffer.size: 320MB
    alluxio.security.stale.channel.purge.interval: 365d
    alluxio.user.metadata.cache.enabled: "false"
    alluxio.user.metadata.cache.max.size: "1000000"
    alluxio.user.direct.memory.io.enabled: "true"
    alluxio.fuse.cached.paths.max: "1000000"
    alluxio.job.worker.threadpool.size: "64"
    alluxio.worker.block.master.client.pool.size: 128


tieredstore:
  levels:
  - alias: MEM
    level: 0
    path: /dev/shm
    type: hostPath
    # quota: 120GB
    high: 0.99
    low: 0.7

fuse:
  image: alluxio/alluxio-fuse
  imageTag: "2.1.1"
  imagePullPolicy: Always
  args:
    - fuse
    - --fuse-opts=direct_io
```

5. Load all the data into allxuio
6. Run the training job
7. Get the performance result:

```
----------------------------------------------------------------
1000	images/sec: 620.6 +/- 7.8 (jitter = 264.4)	4.721
----------------------------------------------------------------
total images/sec: 4963.33
----------------------------------------------------------------
```

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
