### ISSUE TITLE
Helm indent introduced extra whitespace on previous row

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#10724]
**Summary**
Helm indent function causes incorrectly whitespace on previously line. This might not be directly related to `indent`, as other usage of `indent` don't seem to go wrong. But this is definitely related to how `indent` works together with how we do templating.

**Example:**
```
          volumeMounts:
            - name: alluxio-domain
              mountPath: /opt/domain
            {{- if .Values.secrets -}}
              {{- if .Values.secrets.worker -}}
{{- include "alluxio.worker.secretVolumeMounts" . | indent 12 -}}
              {{- end -}}
            {{- end -}}
```
Will result in the following. Note there are exactly 12 spaces after `/opt/domain`. This number 12 actually changes with different argument to `indent`.
```
          volumeMounts:
            - name: alluxio-domain
              mountPath: /opt/domain            
            - name: secret-alluxio-hdfs-config-volume
              mountPath: /secrets/hdfsConfig
              readOnly: true            
```

Templating without indent will result in no extra whitespace on previous line but block not indented correctly. Namely do `{{- include "alluxio.worker.secretVolumeMounts" . -}}`.
```
            - name: alluxio-domain
              mountPath: /opt/domain
- name: secret-alluxio-hdfs-config-volume
  mountPath: /secrets/hdfsConfig
  readOnly: true          
```

**Urgency**
Low
