### ISSUE TITLE
AlluxioWorker在低水位下发生数据驱逐

### ISSUE THREAD

**Issue by iluoeli** [Alluxio/alluxio#11435]
**Alluxio Version:**
2.3.0-SNAPSHOT

**Describe the bug**
在未缓存任何数据的Alluxio集群中运行机器学习任务，期间持续观察缓存状况，在水位较低的情况下，仍然会发生数据驱逐现象。
[alluxio-capacity.txt](https://github.com/Alluxio/alluxio/files/4632096/alluxio-capacity.txt)
[diagnose_alluxio_1589457230.tar.gz](https://github.com/Alluxio/alluxio/files/4632097/diagnose_alluxio_1589457230.tar.gz)

``` bash
bash-4.4# alluxio fs free -f /
/ was successfully freed from Alluxio space.
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 0B
        Tier: MEM  Size: 0B
    Used Percentage: 0%
    Free Percentage: 100%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          0B (0%)
192.168.1.15     0                capacity      220.27GB
                                  used          0B (0%)
192.168.1.11     0                capacity      220.27GB
                                  used          0B (0%)
192.168.1.16     0                capacity      220.27GB
                                  used          0B (0%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 118.80GB
        Tier: MEM  Size: 118.80GB
    Used Percentage: 13%
    Free Percentage: 87%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          32.76GB (14%)
192.168.1.15     0                capacity      220.27GB
                                  used          33.01GB (14%)
192.168.1.11     0                capacity      220.27GB
                                  used          31.63GB (14%)
192.168.1.16     0                capacity      220.27GB
                                  used          21.40GB (9%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 133.47GB
        Tier: MEM  Size: 133.47GB
    Used Percentage: 15%
    Free Percentage: 85%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          37.50GB (17%)
192.168.1.15     0                capacity      220.27GB
                                  used          36.03GB (16%)
192.168.1.11     0                capacity      220.27GB
                                  used          36.50GB (16%)
192.168.1.16     0                capacity      220.27GB
                                  used          23.43GB (10%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 117.12GB
        Tier: MEM  Size: 117.12GB
    Used Percentage: 13%
    Free Percentage: 87%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          25.71GB (11%)
192.168.1.15     0                capacity      220.27GB
                                  used          26.55GB (12%)
192.168.1.11     0                capacity      220.27GB
                                  used          28.75GB (13%)
192.168.1.16     0                capacity      220.27GB
                                  used          36.11GB (16%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 128.19GB
        Tier: MEM  Size: 128.19GB
    Used Percentage: 14%
    Free Percentage: 86%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          39.52GB (17%)
192.168.1.15     0                capacity      220.27GB
                                  used          30.47GB (13%)
192.168.1.11     0                capacity      220.27GB
                                  used          32.95GB (14%)
192.168.1.16     0                capacity      220.27GB
                                  used          25.25GB (11%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 112.59GB
        Tier: MEM  Size: 112.59GB
    Used Percentage: 12%
    Free Percentage: 88%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          22.92GB (10%)
192.168.1.15     0                capacity      220.27GB
                                  used          23.72GB (10%)
192.168.1.11     0                capacity      220.27GB
                                  used          24.16GB (10%)
192.168.1.16     0                capacity      220.27GB
                                  used          41.79GB (18%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 83.44GB
        Tier: MEM  Size: 83.44GB
    Used Percentage: 9%
    Free Percentage: 91%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          19.13GB (8%)
192.168.1.15     0                capacity      220.27GB
                                  used          19.76GB (8%)
192.168.1.11     0                capacity      220.27GB
                                  used          19.56GB (8%)
192.168.1.16     0                capacity      220.27GB
                                  used          25.00GB (11%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 77.07GB
        Tier: MEM  Size: 77.07GB
    Used Percentage: 8%
    Free Percentage: 92%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          19.13GB (8%)
192.168.1.15     0                capacity      220.27GB
                                  used          19.14GB (8%)
192.168.1.11     0                capacity      220.27GB
                                  used          19.25GB (8%)
192.168.1.16     0                capacity      220.27GB
                                  used          19.55GB (8%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 77.07GB
        Tier: MEM  Size: 77.07GB
    Used Percentage: 8%
    Free Percentage: 92%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          19.13GB (8%)
192.168.1.15     0                capacity      220.27GB
                                  used          19.14GB (8%)
192.168.1.11     0                capacity      220.27GB
                                  used          19.25GB (8%)
192.168.1.16     0                capacity      220.27GB
                                  used          19.55GB (8%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 77.07GB
        Tier: MEM  Size: 77.07GB
    Used Percentage: 8%
    Free Percentage: 92%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          19.13GB (8%)
192.168.1.15     0                capacity      220.27GB
                                  used          19.14GB (8%)
192.168.1.11     0                capacity      220.27GB
                                  used          19.25GB (8%)
192.168.1.16     0                capacity      220.27GB
                                  used          19.55GB (8%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 77.07GB
        Tier: MEM  Size: 77.07GB
    Used Percentage: 8%
    Free Percentage: 92%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          19.13GB (8%)
192.168.1.15     0                capacity      220.27GB
                                  used          19.14GB (8%)
192.168.1.11     0                capacity      220.27GB
                                  used          19.25GB (8%)
192.168.1.16     0                capacity      220.27GB
                                  used          19.55GB (8%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 153.16GB
        Tier: MEM  Size: 153.16GB
    Used Percentage: 17%
    Free Percentage: 83%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          39.08GB (17%)
192.168.1.15     0                capacity      220.27GB
                                  used          35.88GB (16%)
192.168.1.11     0                capacity      220.27GB
                                  used          37.11GB (16%)
192.168.1.16     0                capacity      220.27GB
                                  used          41.09GB (18%)
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers: 
    Total Capacity: 881.07GB
        Tier: MEM  Size: 881.07GB
    Used Capacity: 110.89GB
        Tier: MEM  Size: 110.89GB
    Used Percentage: 12%
    Free Percentage: 88%

Worker Name      Last Heartbeat   Storage       MEM
192.168.1.17     0                capacity      220.27GB
                                  used          26.91GB (12%)
192.168.1.15     0                capacity      220.27GB
                                  used          29.11GB (13%)
192.168.1.11     0                capacity      220.27GB
                                  used          27.22GB (12%)
192.168.1.16     0                capacity      220.27GB
                                  used          27.65GB (12%)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by iluoeli** [comment]
Master，Worker，Fuse配置如下：
```
properties:
    alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    alluxio.fuse.jnifuse.enabled: true
    # It should be great than (120)*0.01 = 2GB
    alluxio.fuse.debug.enabled: "false"
    alluxio.web.ui.enabled: false
    alluxio.user.file.writetype.default: MUST_CACHE
    alluxio.user.block.write.location.policy.class: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    alluxio.worker.allocator.class: alluxio.worker.block.allocator.GreedyAllocator
    alluxio.user.block.size.bytes.default: 32MB
    fs.oss.endpoint: oss-cn-shanghai-internal.aliyuncs.com
    # set OSS endpoint
    fs.oss.accessKeyId: LTAIeNWmUog8incm
    fs.oss.accessKeySecret: 6nRkXNZ4VnS46rTPeKveEtqb5bElJY
    alluxio.master.mount.table.root.ufs: oss://imagenet-shanghai-data/
    # alluxio.underfs.oss.socket.timeout: 3000sec
    alluxio.user.streaming.reader.chunk.size.bytes: 32MB
    alluxio.user.local.reader.chunk.size.bytes: 32MB
    alluxio.worker.network.reader.buffer.size: 32MB
    alluxio.worker.file.buffer.size: 320MB
    alluxio.job.worker.threadpool.size: 64
    alluxio.user.metrics.collection.enabled: false
    alluxio.master.rpc.executor.max.pool.size: 10240
    alluxio.master.rpc.executor.core.pool.size: 128
    alluxio.master.mount.table.root.readonly: true
    alluxio.user.update.file.accesstime.disabled: true
    alluxio.user.file.passive.cache.enabled: false
    alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 2GB
    alluxio.master.journal.folder: /journal
    alluxio.master.journal.type: UFS
    alluxio.user.block.master.client.pool.gc.threshold: 2day
    alluxio.user.file.master.client.threads: 1024
    alluxio.user.block.master.client.threads: 1024
    alluxio.user.file.readtype.default: CACHE
    alluxio.security.stale.channel.purge.interval: 365d
    alluxio.user.metadata.cache.enabled: true
    alluxio.user.metadata.cache.expiration.time: 2day
    alluxio.user.metadata.cache.max.size: "1000000"
    alluxio.user.direct.memory.io.enabled: true
    alluxio.fuse.cached.paths.max: "1000000"
    alluxio.job.worker.threadpool.size: 164
    alluxio.user.worker.list.refresh.interval: 2min
    alluxio.user.logging.threshold: 1000ms
    alluxio.fuse.logging.threshold: 1000ms
    alluxio.worker.block.master.client.pool.size: 1024

worker:
    jvmOptions: " -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:MaxDirectMemorySize=32g  -XX:ActiveProcessorCount=8 "

master:
    jvmOptions: " -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:ActiveProcessorCount=8 "

tieredstore:
  levels:
  - alias: MEM
    level: 0
    type: hostPath
    path: /dev/shm
    #quota: 180GB
    high: 0.99
    low: 0.8

fuse:
  image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio-fuse
  imageTag: "2.3.0-SNAPSHOT-8cc322a"
  imagePullPolicy: Always
  env:
    MAX_IDLE_THREADS: "64"
    SPENT_TIME: "1000"
  # Customize the MaxDirectMemorySize
  jvmOptions: " -Xmx16G -Xms16G -XX:+UseG1GC -XX:MaxDirectMemorySize=32g -XX:+UnlockExperimentalVMOptions -XX:ActiveProcessorCount=24 "
  shortCircuitPolicy: local
  args:
    - fuse
    - --fuse-opts=direct_io,ro,max_read=131072,attr_timeout=7200,entry_timeout=7200
```
