### ISSUE TITLE
The multiple mediumtypes can't work

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#11778]
**Alluxio Version:**
2.3.0
alluxio helm chart: 0.6.8
helm3

**Describe the bug**
I install the alluxio with helm with the following value yaml

```yaml
tieredstore:
  levels:
    - level: 0
      alias: HDD
      mediumtype: MEM,SSD
      path: /mnt/disk1,/mnt/disk2
      type: hostPath
      quota: 1024G,1024G
      high: 0.95
      low: 0.7
```

it's expected that mediumtype="MEM,SSD", mediumName resolves to mem-0 and ssd-1. But when I run `helm template -f value.yaml alluxio`

The result is 

```
volumeMounts:
            - name: alluxio-domain
              mountPath: /opt/domain
            - mountPath: /mnt/disk1
              name: mem-
            - mountPath: /mnt/disk2
              name: ssd-
```

But it's illegal.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
1. Download the helm chart
```
git clone https://github.com/Alluxio/alluxio.git
cd alluxio/integration/kubernetes/helm-chart/
```

2.Create the the yaml

```yaml
tieredstore:
  levels:
    - level: 0
      alias: HDD
      mediumtype: MEM,SSD
      path: /mnt/disk1,/mnt/disk2
      type: hostPath
      quota: 1024G,1024G
      high: 0.95
      low: 0.7
```

3. Generate the template

```
helm template -f value.yaml alluxio
```

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
