### ISSUE TITLE
alluxio worker cannot be started on openshift4.6 with crio

### ISSUE THREAD

**Issue by xpflying** [Alluxio/alluxio#12664]
**Alluxio Version:**
deloy Alluxio 2.4.1 with helm

**Describe the bug**
alluxio worker cannot be started on openshift4.6 with crio, The default worker configuration is alluxio.worker.tieredstore.level0.dirs.quota=1G，When the aluxio worker starts, the error message is as follows,
 **tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured size: 1024.00MB**
```
# oc logs -f alluxio-worker-9w6p4 -c alluxio-worker 
2020-12-18 07:13:32,281 INFO  NettyUtils - EPOLL_MODE is available
2020-12-18 07:13:32,616 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.26.41, rack=null)
2020-12-18 07:13:32,817 INFO  BlockWorkerFactory - Creating alluxio.worker.block.BlockWorker 
2020-12-18 07:13:32,870 ERROR AlluxioWorker - Fatal error: Failed to create worker process
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured size: 1024.00MB
        at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:168)
        at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:46)
        at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:38)
        at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:72)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured size: 1024.00MB
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:592)
        at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:554)
        at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:118)
        ... 3 more
Caused by: java.lang.IllegalStateException: tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured size: 1024.00MB
        at alluxio.worker.block.meta.StorageTier.checkEnoughMemSpace(StorageTier.java:176)
        at alluxio.worker.block.meta.StorageTier.initStorageTier(StorageTier.java:129)
        at alluxio.worker.block.meta.StorageTier.newStorageTier(StorageTier.java:200)
        at alluxio.worker.block.BlockMetadataManager.<init>(BlockMetadataManager.java:78)
        at alluxio.worker.block.BlockMetadataManager.createBlockMetadataManager(BlockMetadataManager.java:114)
        at alluxio.worker.block.TieredBlockStore.<init>(TieredBlockStore.java:116)
        at alluxio.worker.block.DefaultBlockWorker.<init>(DefaultBlockWorker.java:132)
        at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:43)
        at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:26)
        at alluxio.worker.AlluxioWorkerProcess.lambda$new$0(AlluxioWorkerProcess.java:110)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
The following information is obtained by changing aluxio.worker.tieredstore.level0.dirs.quota to 64M and going into the aluxio worker pod.
```
# oc exec -it alluxio-worker-7dc4c -c alluxio-worker -- /bin/sh
/opt/alluxio-2.4.1 $ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 199.5G     91.7G    107.8G  46% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    31.5G         0     31.5G   0% /sys/fs/cgroup
shm                      31.5G         0     31.5G   0% /dev/shm
tmpfs                    31.5G     69.1M     31.4G   0% /etc/resolv.conf
tmpfs                    31.5G     69.1M     31.4G   0% /etc/hostname
tmpfs                    31.5G     12.0K     31.5G   0% /secrets/hdfsConfig
tmpfs                    31.5G         0     31.5G   0% /dev/shm
/dev/mapper/coreos-luks-root-nocrypt
                        199.5G     91.7G    107.8G  46% /etc/hosts
/dev/mapper/coreos-luks-root-nocrypt
                        199.5G     91.7G    107.8G  46% /dev/termination-log
tmpfs                    31.5G     69.1M     31.4G   0% /run/secrets
tmpfs                    31.5G     32.0K     31.5G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    31.5G         0     31.5G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                    31.5G         0     31.5G   0% /proc/scsi
tmpfs                    31.5G         0     31.5G   0% /sys/firmware

/opt/alluxio-2.4.1 $ mount 
overlay on / type overlay (rw,context="system_u:object_r:container_file_t:s0:c0,c25",relatime,lowerdir=/var/lib/containers/storage/overlay/l/BCPJZHTUCROS4OIVCAO5N3OKBR:/var/lib/containers/storage/overlay/l/DPL6JO62EL2UO6JFMBS3EHYTDB:/var/lib/containers/storage/overlay/l/LIEHUM4SDJE7UJBDLAHD4SAZRI:/var/lib/containers/storage/overlay/l/PWH7AIDVWLICN6QIW35VGPLQTY:/var/lib/containers/storage/overlay/l/GD7C2SRBCTR6SDJXHXY2OVDE6V:/var/lib/containers/storage/overlay/l/AFV7EWEB2ZPO7DAPNEDULCZ3P6:/var/lib/containers/storage/overlay/l/AX2U7DF3Y6VRQCIQJZEL524KNE:/var/lib/containers/storage/overlay/l/ZECA3BOJEYADRN7LLCZ6KPTULM:/var/lib/containers/storage/overlay/l/G7SHKCHLGNHLJWLW6MVBAIRW43,upperdir=/var/lib/containers/storage/overlay/f6d7be686b6077b47522d958d2357212940639fe7d12468aaeed71264f91840d/diff,workdir=/var/lib/containers/storage/overlay/f6d7be686b6077b47522d958d2357212940639fe7d12468aaeed71264f91840d/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,seclabel,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,seclabel,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/rdma type cgroup (ro,seclabel,nosuid,nodev,noexec,relatime,rdma)
shm on /dev/shm type tmpfs (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /etc/resolv.conf type tmpfs (rw,seclabel,nosuid,nodev,noexec,mode=755)
tmpfs on /etc/hostname type tmpfs (rw,seclabel,nosuid,nodev,mode=755)
tmpfs on /secrets/hdfsConfig type tmpfs (ro,seclabel,relatime)
tmpfs on /dev/shm type tmpfs (rw,seclabel,relatime)
/dev/mapper/coreos-luks-root-nocrypt on /etc/hosts type xfs (rw,seclabel,relatime,attr2,inode64,prjquota)
/dev/mapper/coreos-luks-root-nocrypt on /dev/termination-log type xfs (rw,seclabel,relatime,attr2,inode64,prjquota)
tmpfs on /run/secrets type tmpfs (rw,seclabel,nosuid,nodev,mode=755)
tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,seclabel,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/acpi type tmpfs (ro,context="system_u:object_r:container_file_t:s0:c0,c25",relatime)
tmpfs on /proc/kcore type tmpfs (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,context="system_u:object_r:container_file_t:s0:c0,c25",nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,context="system_u:object_r:container_file_t:s0:c0,c25",relatime)
tmpfs on /sys/firmware type tmpfs (ro,context="system_u:object_r:container_file_t:s0:c0,c25",relatime)
```

**Comment by gpang** [comment]
@xpflying Thanks for this report. Was the worker formatted with only `64mb` first, and then started with `1g`?

**Comment by xpflying** [comment]
@gpang Here is the default configuration, when using this, the logs of the aluxio-worker pod indicate that tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured size: 1024.00MB, and is in CrashLoopBackOff state.So I changed aluxio.worker.tieredstore.level0.dirs.quota to 64M, so I could get into the pod and use the mount, df -h command to get the information.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: alluxio-config
  labels:
    name: alluxio-config
    app: alluxio
data:
  ALLUXIO_JAVA_OPTS: |-
    -Dalluxio.master.hostname=alluxio-master-0 -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal -Dalluxio.security.stale.channel.purge.interval=365d
  ALLUXIO_MASTER_JAVA_OPTS: |-
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME}
  ALLUXIO_JOB_MASTER_JAVA_OPTS: |-
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME}
  ALLUXIO_WORKER_JAVA_OPTS: |-
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} -Dalluxio.worker.rpc.port=29999 -Dalluxio.worker.web.port=30000 -Dalluxio.user.short.circuit.enabled=false -Dalluxio.worker.container.hostname=${ALLUXIO_WORKER_CONTAINER_HOSTNAME} -Dalluxio.worker.ramdisk.size=2G -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=MEM -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=MEM -Dalluxio.worker.tieredstore.level0.dirs.path=/dev/shm -Dalluxio.worker.tieredstore.level0.dirs.quota=1G -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95 -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7
  ALLUXIO_JOB_WORKER_JAVA_OPTS: |-
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} -Dalluxio.job.worker.rpc.port=30001 -Dalluxio.job.worker.data.port=30002 -Dalluxio.job.worker.web.port=30003
  ALLUXIO_FUSE_JAVA_OPTS: |-
    -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME} -XX:MaxDirectMemorySize=2g
  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: /dev/shm
```
```
      containers:
        - name: alluxio-worker
          image: alluxio/alluxio:2.4.1
          resources:
            limits:
              memory: 4G
            requests:
              memory: 2G
          command: ["tini", "--", "/entrypoint.sh"]
          args:
            - worker-only
            - --no-format
          envFrom:
          - configMapRef:
              name: alluxio-config
          volumeMounts:
            - mountPath: /dev/shm
              name: mem
      volumes:
        - name: mem
          emptyDir:
            medium: "Memory"
            sizeLimit: 1G
```

**Comment by apc999** [comment]
@xpflying  error message `tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured size: 1024.00MB` suggests when your worker starts, it only sees 64MB as tempfs capacity, smaller than what you configured in the following

```
volumes:
        - name: mem
          emptyDir:
            medium: "Memory"
            sizeLimit: 1G
```

If you don't have enough tempfs capacity (1GB as specified), you can use SSD or local disk for Alluxio caching space rather than tempfs.
check how to configure it  here https://docs.alluxio.io/os/user/stable/en/core-services/Caching.html#configuring-alluxio-storage
