### ISSUE TITLE
Enhance CSI - add pathType field in storage class.

### ISSUE THREAD

**Issue by Binyang2014** [Alluxio/alluxio#13782]
Currently,  alluxio CSI will only mount directory if it present in alluxio namespace.
Add pathType to dynamic create directory if it is not present.

The valid pathType can be: `DirectoryOrCreate`, `Directory`. `Directory` is the default value.

If we use `DirectoryOrCreate` as the path type,  if the directory is not present in alluxio namespace, CSI server plugin will create it automatically. 

If we use `Directory` as the path type, if the directory is not present in alluxio namespace, error will return with some error message.

Updated storageClass config:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alluxio
provisioner: alluxio
parameters:
  alluxioPath: /data
  pathType: DirectoryOrCreate
  javaOptions: "-Dalluxio.user.metadata.cache.enabled=true "
volumeBindingMode: Immediate
mountOptions:
  - kernel_cache
  - allow_other
  - entry_timeout=36000
  - attr_timeout=36000
  - max_readahead=0
```
