### ISSUE TITLE
Cannot run alluxio-csi successfully from alluxio-csi yaml generated by helm-generated.sh

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13843]
**Alluxio Version:**
master 27f81a97

**Describe the bug**

Cannot run alluxio-csi successfully from alluxio-csi yaml generated by helm-generated.sh or through the README.md

**To Reproduce**

```bash
integration/kubernetes/helm-generate.sh  multi-embedded
kubectl apply -f integration/kubernetes/multiMaster-embeddedJournal/csi
```

The `/data` cannot see the alluxio filesystem. After some carefully deep in the source code, I think it lack of `alluxio.master.hostname` `VolumeContext` here.

**Expected behavior**

Alluxio fuse can mount successfully, volume can publish.

**Urgency**

Urgent

**Additional context**
No

**Comment by maobaolong** [comment]
@Binyang2014 Would you please have a try alluxio-csi in your test k8s cluster? I think newbies like me cannot easy to use alluxio-csi in their production.

**Comment by Binyang2014** [comment]
@maobaolong, Can you provide your config? How do you deploy alluxio-master, do you deploy the master-service? It seems caused by DNS issue. Please make sure the master service is deployed and your core-dns works fine. It's better to provide yaml config.

BTW, we did have some bugs and fixed in this PR: https://github.com/Alluxio/alluxio/pull/13813. I tested this PR in my test bed and it works.

**Comment by maobaolong** [comment]
@Binyang2014 Thanks for the reply, it really helps. I change the master_ips to ip addresses, it can work in my env now. 

And how about the other issues mentioned in the description of this issue?

- `Invalid property key ALLUXIO_CLIENT_HOSTNAME`. Maybe csi-nodeplugin would need to generated alluxio-env.sh like Alluxio entrypoint.sh does.
- DNS issue. Use hostNetwork
- Displayed the pv and pvc is successfully created even actually, the alluxio-fuse is not started successfully.

**Comment by Binyang2014** [comment]
1. For `ALLUXIO_CLIENT_HOSTNAME`, can you provide your alluxio-config, I don't meet this issue in my env, need to check to config to find the root cause.
2. For dns issue, add `dnsPolicy: ClusterFirstWithHostNet` will solve this.
3. For pv/pvc issue. It seems due to we mixed the  static and dynamic provision methods. Please make sure you not deployed pv.yaml and pvc-static.yaml under csi folder. We need to enhance the doc to fix it

**Comment by maobaolong** [comment]
@Binyang2014 
1. This is my alluxio-config, I have to use ALLUXIO_CLIENT_HOSTNAME, because our fuse are deploy to the same node with Alluxio worker, this env var can ensure short-circuit work.

```yaml
---
# Source: alluxio/templates/config/alluxio-conf.yaml
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#


apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: alluxio-config
  labels:
    name: alluxio-config
    app: alluxio
    chart: alluxio-0.6.23
    release: alluxio
    heritage: Helm
data:
  ALLUXIO_JAVA_OPTS: |-
    -Dalluxio.user.metrics.collection.enabled=true -Dalluxio.user.file.writetype.default=CACHE_THROUGH -Dalluxio.master.audit.logging.enabled=true -Dalluxio.master.update.check.enabled=false -Dalluxio.master.journal.type=EMBEDDED -Dalluxio.master.journal.folder=/journal -Dalluxio.master.embedded.journal.addresses=,alluxio-master-0:19200,alluxio-master-1:19200,alluxio-master-2:19200 -Dalluxio.security.stale.channel.purge.interval=365d -Dalluxio.conf.dynamic.update.enabled=true -Dalluxio.worker.rpc.port=29999 -Dalluxio.worker.web.port=30000 -Dalluxio.worker.data.server.domain.socket.address=/opt/domain -Dalluxio.worker.data.server.domain.socket.as.uuid=true  -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=MEM -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=MEM -Dalluxio.worker.tieredstore.level0.dirs.path=/dev/shm -Dalluxio.worker.tieredstore.level0.dirs.quota=4G -Dalluxio.worker.tieredstore.free.ahead.bytes=1G
  ALLUXIO_MASTER_JAVA_OPTS: |-
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} 
  ALLUXIO_JOB_MASTER_JAVA_OPTS: |-
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} -Dalluxio.worker.container.hostname=${ALLUXIO_WORKER_CONTAINER_HOSTNAME}
  ALLUXIO_WORKER_JAVA_OPTS: |-
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME}
  ALLUXIO_JOB_WORKER_JAVA_OPTS: |-
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} -Dalluxio.job.worker.rpc.port=30001 -Dalluxio.job.worker.data.port=30002 -Dalluxio.job.worker.web.port=30003
  ALLUXIO_FUSE_JAVA_OPTS: |-
    -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME}
  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: /dev/shm

```

2. Thanks for add it to this PR.
3. Yeah, I have a double check, and make sure I don't start pvc-static and pv. and start nginx-example pod successfully, eventually, I see a empty directory `/data` in the nginx-example pod, I found error in the `fuse.out` within the `csi-node-plugin` pod, so the alluxio-fuse didn't started successfully but we see everything goes normally without any failure from the pod or container status.
