### ISSUE TITLE
helm部署alluxio报错

### ISSUE THREAD

**Issue by lgy1027** [Alluxio/alluxio#14260]
alluxio：2.6.2
开启fuse，fuse挂载的本地目录没有访问权限，fuse是基于worker开启

配置：
alluxio-config.yaml
````
apiVersion: v1
data:
  ALLUXIO_JAVA_OPTS: '-Dalluxio.master.hostname=alluxio-master-0 -Dalluxio.master.journal.type=UFS
    -Dalluxio.master.journal.folder=/journal -Dalluxio.master.mount.table.root.ufs=/datasets/lgy
    -Dalluxio.security.authorization.permission.enabled=false -Dalluxio.security.authorization.permission.umask=0
    -Dalluxio.security.stale.channel.purge.interval=365d -Dalluxio.user.file.metadata.sync.interval=2m
    -Dalluxio.user.file.passive.cache.enabled=false -Dalluxio.user.file.readtype.default=CACHE
    -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    -Dalluxio.work.fuse.user.group.translation.enabled=false '
  ALLUXIO_JOB_MASTER_JAVA_OPTS: '-Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} '
  ALLUXIO_JOB_WORKER_JAVA_OPTS: '-Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME}
    -Dalluxio.job.worker.rpc.port=30001 -Dalluxio.job.worker.data.port=30002 -Dalluxio.job.worker.web.port=30003 '
  ALLUXIO_MASTER_JAVA_OPTS: '-Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} '
  ALLUXIO_WORKER_JAVA_OPTS: '-Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME}
    -Dalluxio.worker.rpc.port=29999 -Dalluxio.worker.web.port=30000 -Dalluxio.worker.fuse.enabled=true
    -Dalluxio.worker.fuse.mount.alluxio.path=/ -Dalluxio.worker.fuse.mount.point=/mnt/alluxio-fuse
    -Dalluxiuo.worker.fuse.mount.options=allow_other -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME}
    -XX:MaxDirectMemorySize=2g -Dalluxio.worker.data.server.domain.socket.address=/opt/domain
    -Dalluxio.worker.data.server.domain.socket.as.uuid=true -Dalluxio.worker.container.hostname=${ALLUXIO_WORKER_CONTAINER_HOSTNAME}
    -Dalluxio.worker.ramdisk.size=2G -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=MEM
    -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=MEM -Dalluxio.worker.tieredstore.level0.dirs.path=/dev/shm
    -Dalluxio.worker.tieredstore.level0.dirs.quota=1G -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95
    -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7 '
  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: /dev/shm
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: alluxio
    chart: alluxio-0.6.27
    heritage: Helm
    name: alluxio-config
    release: alluxio
  name: alluxio-config
  namespace: lgy
````
alluxio-master.yaml
````
piVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: alluxio
    meta.helm.sh/release-namespace: lgy
  labels:
    app: alluxio
    app.kubernetes.io/managed-by: Helm
    chart: alluxio-0.6.27
    heritage: Helm
    name: alluxio-master
    release: alluxio
    role: alluxio-master
  name: alluxio-master
  namespace: lgy
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alluxio
      name: alluxio-master
      role: alluxio-master
  serviceName: alluxio-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alluxio
        chart: alluxio-0.6.27
        heritage: Helm
        name: alluxio-master
        release: alluxio
        role: alluxio-master
    spec:
      containers:
        - args:
            - master-only
            - --no-format
          command:
            - tini
            - --
            - /entrypoint.sh
          env:
            - name: ALLUXIO_MASTER_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: alluxio-config
          image: alluxio/alluxio:2.6.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: rpc
            timeoutSeconds: 5
          name: alluxio-master
          ports:
            - containerPort: 19998
              name: rpc
              protocol: TCP
            - containerPort: 19999
              name: web
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: rpc
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 8G
            requests:
              cpu: "1"
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datasets/lgy
              name: ufs
            - mountPath: /journal
              name: alluxio-journal
        - args:
            - job-master
          command:
            - tini
            - --
            - /entrypoint.sh
          env:
            - name: ALLUXIO_MASTER_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: alluxio-config
          image: alluxio/alluxio:2.6.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: job-rpc
            timeoutSeconds: 5
          name: alluxio-job-master
          ports:
            - containerPort: 20001
              name: job-rpc
              protocol: TCP
            - containerPort: 20002
              name: job-web
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: job-rpc
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 8G
            requests:
              cpu: "1"
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datasets/lgy
              name: ufs
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - alluxio
            - formatJournal
          image: alluxio/alluxio:2.6.2
          imagePullPolicy: IfNotPresent
          name: journal-format
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /journal
              name: alluxio-journal
      nodeSelector:
        alluxio: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /datasets/lgy
            type: ""
          name: ufs
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: alluxio-journal
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: leinaoyun
        volumeMode: Filesystem
````

alluxio-work.yaml
````
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: alluxio
    meta.helm.sh/release-namespace: lgy
  labels:
    app: alluxio
    app.kubernetes.io/managed-by: Helm
    chart: alluxio-0.6.27
    heritage: Helm
    release: alluxio
    role: alluxio-worker
  name: alluxio-worker
  namespace: lgy
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alluxio
      release: alluxio
      role: alluxio-worker
  template:
    metadata:
      labels:
        app: alluxio
        chart: alluxio-0.6.27
        heritage: Helm
        release: alluxio
        role: alluxio-worker
    spec:
      containers:
        - args:
            - worker-only
            - --no-format
          command:
            - tini
            - --
            - /entrypoint.sh
          env:
            - name: ALLUXIO_WORKER_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: ALLUXIO_WORKER_CONTAINER_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ALLUXIO_CLIENT_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: alluxio-config
          image: alluxio/alluxio:2.6.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: rpc
            timeoutSeconds: 5
          name: alluxio-worker
          ports:
            - containerPort: 29999
              name: rpc
              protocol: TCP
            - containerPort: 30000
              name: web
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: rpc
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 4G
            requests:
              cpu: "1"
              memory: 2G
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datasets/lgy
              name: ufs
            - mountPath: /opt/domain
              name: alluxio-domain
            - mountPath: /dev/shm
              name: mem
            - mountPath: /dev/fuse
              name: alluxio-fuse-device
            - mountPath: /mnt
              mountPropagation: Bidirectional
              name: alluxio-fuse-mount
        - args:
            - job-worker
          command:
            - tini
            - --
            - /entrypoint.sh
          env:
            - name: ALLUXIO_WORKER_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: ALLUXIO_WORKER_CONTAINER_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: alluxio-config
          image: alluxio/alluxio:2.6.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: job-rpc
            timeoutSeconds: 5
          name: alluxio-job-worker
          ports:
            - containerPort: 30001
              name: job-rpc
              protocol: TCP
            - containerPort: 30002
              name: job-data
              protocol: TCP
            - containerPort: 30003
              name: job-web
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: job-rpc
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 4G
            requests:
              cpu: "1"
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datasets/lgy
              name: ufs
            - mountPath: /opt/domain
              name: alluxio-domain
            - mountPath: /dev/shm
              name: mem
      dnsPolicy: ClusterFirst
      nodeSelector:
        alluxio: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /datasets/lgy
            type: ""
          name: ufs
        - hostPath:
            path: /tmp/alluxio-domain
            type: DirectoryOrCreate
          name: alluxio-domain
        - emptyDir:
            medium: Memory
            sizeLimit: 1G
          name: mem
        - hostPath:
            path: /dev/fuse
            type: CharDevice
          name: alluxio-fuse-device
        - hostPath:
            path: /mnt
            type: Directory
          name: alluxio-fuse-mount
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
````
目前部署存在的问题：
1、fuse挂载盘/mnt/alluxio-fuse没有操作权限
![image](https://user-images.githubusercontent.com/38779388/137315450-b7c18bcf-1643-42b9-8833-932076f847b0.png)
2、配置alluxio.user.file.metadata.sync.interval=2m情况下，在UFS删除文件后，Pod中使用alluxio fs ls / 命令行查看对应文件已删除，但宿主机上FUSE挂载点/mnt/alluxio-fuse下对应文件未自动删除。
