### ISSUE TITLE
PodDisruptionBudget for alluxio-master

### ISSUE THREAD

**Issue by kwnam1302** [Alluxio/alluxio#14279]
**Is your feature request related to a problem? Please describe.**

Multiple-instance Stateful application requires setting the PodDisruptionBudget.
https://kubernetes.io/docs/tasks/run-application/configure-pdb/#think-about-how-your-application-reacts-to-disruptions
Currently, the PodDisruptionBudget for alluxio-master is not set when installing alluxio on k8s.

**Describe the solution you'd like**

After installing Alluxio, I added it manually as below.

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: alluxio-master-pdb
  namespace: alluxio
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: alluxio-master
```

**Describe alternatives you've considered**

I think it would be good if the PodDisruptionBudget for alluxio-master is generated using helm

**Urgency**
not urgency. 

**Additional context**
