### ISSUE TITLE
Alluxio failed to create 4 replication of data with distributedLoad

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14274]
**Alluxio Version:**
Alluxio 2.6.2

**Describe the bug**
With a folder with imagenet dataset 1.3 million * 105 KB each = 130GB dataset.
`bin/alluxio fs distributedLoad --replication 4 /dali`
only loaded 380GB dataset instead of 130GB * 4 = 520GB.
- the command succeeds
- no job failed in bin/alluxio job ls
- no error logs in worker or job worker or job master

some files have four block locations which are correct.
Some files only have one/two/three block locations.
The file metadata already set to --replicationMin = 4 and replicationMax=4, so rerunning `bin/alluxio fs setReplication --min 4 --max 4 /fileName` will create a replication job but doesn't do anything. The block locations remain one/two/three as before running this command.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
Expect the bin/alluxio distributedLoad --replication number should replicate to expected replica

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

Configuration
```
data:
  ALLUXIO_JAVA_OPTS: >- 
    -Dalluxio.master.hostname=alluxio-master-0 
    -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal -Dalluxio.master.metastore=ROCKS -Dalluxio.master.metastore.inode.cache.max.size=30000000 
    -Dalluxio.security.authorization.permission.enabled=false -Dalluxio.security.authorization.permission.umask=000 -Dalluxio.security.stale.channel.purge.interval=365d 
    -Dalluxio.master.mount.table.root.ufs=s3://ALLUXIO_S3_ROOT_UFS_BUCKET/ -Daws.accessKeyId=AWS_ACCESS_KEY -Daws.secretKey=AWS_SECRET_ACCESS_KEY
    -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD -Dalluxio.worker.tieredstore.level0.alias=SSD -Dalluxio.worker.tieredstore.level0.dirs.path=/alluxio-cache-ssd -Dalluxio.worker.tieredstore.level0.dirs.quota=300GB -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95  -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7 
    -Dalluxio.underfs.s3.socket.timeout=10min -Dalluxio.underfs.s3.threads.max=10240 -Dalluxio.underfs.s3.admin.threads.max=10240 -Dalluxio.worker.session.timeout.ms=5min 
    -Dalluxio.underfs.s3.request.timeout=0 
    -Dalluxio.underfs.s3.max.error.retry=15
    -Dalluxio.user.block.master.client.pool.size.max=1024 -Dalluxio.user.file.master.client.pool.size.max=1024 -Dalluxio.user.block.worker.client.pool.max=5120
    -Dalluxio.job.worker.threadpool.size=50 
  ALLUXIO_MASTER_JAVA_OPTS: >-
    -Xms52G -Xmx52G 
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} 
    -Dalluxio.master.persistence.blacklist=_temporary 
    -Dalluxio.master.rpc.executor.max.pool.size=10240 -Dalluxio.master.rpc.executor.core.pool.size=128 
    -Dalluxio.master.metastore=ROCKS -Dalluxio.master.metastore.inode.cache.max.size=30000000 -Dalluxio.master.journal.log.size.bytes.max=500MB 
  ALLUXIO_JOB_MASTER_JAVA_OPTS: >- 
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} 
    -Xms32G -Xmx32G 
    -Dalluxio.job.master.job.capacity=5000000 
  ALLUXIO_WORKER_JAVA_OPTS: >-
    -Xmx24G -Xms24G -XX:MaxDirectMemorySize=18g -Xss4m 
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} 
    -Dalluxio.worker.container.hostname=${ALLUXIO_WORKER_CONTAINER_HOSTNAME} 
    -Dalluxio.worker.rpc.port=29999 -Dalluxio.worker.web.port=30000 
    -Dalluxio.worker.data.server.domain.socket.as.uuid=false 
    -Dalluxio.worker.tieredstore.block.locks=100000 
    -Dalluxio.worker.block.master.client.pool.size=1024 
    -Dalluxio.worker.network.reader.buffer.size=32MB 
    -Dalluxio.worker.fuse.enabled=true -Dalluxio.worker.fuse.mount.alluxio.path=/ -Dalluxio.worker.fuse.mount.point=/mnt/alluxio-fuse 
    -Dalluxio.worker.fuse.mount.options=allow_other,kernel_cache,max_read=131072,attr_timeout=7200,entry_timeout=7200 
    -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME} 
    -Dalluxio.user.short.circuit.enabled=true 
    -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.metadata.cache.expiration.time=2h -Dalluxio.user.metadata.cache.max.size=10000000 
    -Dalluxio.user.update.file.accesstime.disabled=true 
    -Dalluxio.user.file.passive.cache.enabled=false 
    -Dalluxio.user.logging.threshold=1000ms -Dalluxio.fuse.logging.threshold=1000ms 
    -Dalluxio.user.block.master.client.pool.gc.threshold=1h 
    -Dalluxio.worker.network.block.reader.threads.max=1024
    -Dalluxio.user.block.read.metrics.enabled=false 
  ALLUXIO_JOB_WORKER_JAVA_OPTS: >- 
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} -Dalluxio.job.worker.rpc.port=30001 -Dalluxio.job.worker.data.port=30002 -Dalluxio.job.worker.web.port=30003 
    -Xmx16G -Xms16G 
  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: /alluxio-cache-ssd
```
Master
```
          resources:
            limits:
              cpu: 8
              memory: 56G
            requests:
              cpu: 8
              memory: 56G
```
job_master
```
          resources:
            limits:
              cpu: 6
              memory: 36G
            requests:
              cpu: 6
              memory: 36G
```
worker
```
          resources:
            limits:
              cpu: 8
              memory: 28G
            requests:
              cpu: 8
              memory: 28G
```
job_worker
```
          resources:
            limits:
              cpu: 4
              memory: 20G
            requests:
              cpu: 4
              memory: 20G
```
