### ISSUE TITLE
WebUI Overview page error when journal type is EMBEDDED with persistentVolume

### ISSUE THREAD

**Issue by packageman** [Alluxio/alluxio#14915]
**Alluxio Version:**
2.7.2

**Describe the bug**
![image](https://user-images.githubusercontent.com/12949466/151114342-185a5614-6aa1-4c83-99ca-14de6e20344d.png)

**To Reproduce**

values.yml

```
journal:
  type: EMBEDDED
  folder: /journal
  volumeType: persistentVolumeClaim
  size: 1Gi
  storageClass: nfs-default
  accessModes:
  - ReadWriteOnce
```

**Expected behavior**
WebUI Overview page can display normally.

**Additional context**
Alluxio master warning log:

```
2022-01-26T06:25:51.057821000Z 2022-01-26 06:25:51,057 WARN  RestUtils - Unexpected error invoking rest endpoint: java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in scheme name at index 0: 192.168.101.4:/nfs-client-provisioner/xxxx-alluxio-journal-alluxio-master-1-pvc-xxxacb3-xxxx-xxxx-87cb-8fca13e731a8
```

File system in alluxio master container:

![image](https://user-images.githubusercontent.com/12949466/151114754-0098a999-11b3-4055-ba2a-ab89818996a8.png)

When changing `journal.volumeType` to `emptyDir` WebUI Overview page can display normally.
