### ISSUE TITLE
java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider

### ISSUE THREAD

**Issue by lmssy** [Alluxio/alluxio#15646]
**Alluxio Version:**
2.7.3

**Describe the bug**
I use kubernetes csi mode to mount a alluxio path to my pod，but the pod start fail with error below:

![image](https://user-images.githubusercontent.com/17894328/170820071-dace0091-aa98-42f2-9544-ae26dd725411.png)

Then I check the  /opt/alluxio-2.7.3/logs/fuse.out on the csi-nodeserver, I can see below error; 
Sometimes the pod can start normally and sometimes fail（seems random）, but each time the pod fail to startup the below error happens。

![image](https://user-images.githubusercontent.com/17894328/170820043-41f0d9d2-df92-4c82-b0de-f2f538676b27.png)
![image](https://user-images.githubusercontent.com/17894328/170820059-1438d0cc-11e3-4b39-9a22-689392d7b1a4.png)

Please help to check, thanks a lot

**Comment by ssz1997** [comment]
Thanks for the report and log. Will look into it.

**Comment by ssz1997** [comment]
@lmssy What version of k8s are you using?

**Comment by lmssy** [comment]
@ssz1997 thanks for your reply
1. kubernetes versio is 1.18.8
2. 6 appliction pods on this node;  the host machine is 8c32g, with 17.5% memory used
3. csi-nodeserver yaml as below

---
# Source: alluxio/templates/csi/nodeplugin.yaml
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#



kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: alluxio-csi-nodeplugin
  labels:
    name: alluxio-csi-nodeplugin
    app: alluxio
    chart: alluxio-0.6.33
    release: alluxio
    heritage: Helm
    role: alluxio-csi-nodeplugin
spec:
  selector:
    matchLabels:
      app: alluxio
      role: alluxio-csi-nodeplugin
      name: alluxio-csi-nodeplugin
  template:
    metadata:
      labels:
        name: alluxio-csi-nodeplugin
        app: alluxio
        chart: alluxio-0.6.33
        release: alluxio
        heritage: Helm
        role: alluxio-csi-nodeplugin
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: node-driver-registrar
          image: registry.cn-shanghai.aliyuncs.com/zebrax/csi-node-driver-registrar:v2.3.0
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/alluxio /registration/alluxio-reg.sock"]
          args:
            - --v=5
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-alluxio-plugin/csi.sock
          resources:
            limits:
              cpu: 100m
              memory: 2000Mi
            requests:
              cpu: 10m
              memory: 1500Mi
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: csi-nodeserver
          # run as root user, mount command need root privilege
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add: ["SYS_ADMIN"]
          resources:
            limits:
              cpu: 4
              memory: 8G
            requests:
              cpu: 1
              memory: 1G
          image: registry.cn-shanghai.aliyuncs.com/zebrax/alluxio:2.7.3
          imagePullPolicy: IfNotPresent
          command: ["tini", "--", "/entrypoint.sh"]
          args :
            - csiserver
            - --v=5
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: ALLUXIO_CLIENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          envFrom:
            - configMapRef:
                name: alluxio-config
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
      nodeSelector:
        workload_type: gpu
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-alluxio-plugin
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir

**Comment by ssz1997** [comment]
@iamaline9477 Thank you for providing the info. My suspicion is the memory for csi nodeserver is not enough because it runs a lot of AlluxioFuse processes. Each application pod is using one fuse process. Currently the total upper bound is 8G , and we have no upperbound for each Fuse process. This means later applications may not have enough memory to even start the fuse process. My suggestion is to set the resources `requests` and `limits` of the csi-nodeserver container to a higher value, for example, 16G.

**Comment by lmssy** [comment]
@ssz1997 I have extend limits to 16G but problem still there, and the host machine is used just by me, no other applications running on it, so the root cause may not related to the resource limits

**Comment by ssz1997** [comment]
@lmssy Did you set the jvm stack size somewhere in the Alluxio config? A small stack may lead to stack overflow.

**Comment by ssz1997** [comment]
@lmssy Another thing you can try is to use the `[alluxio/alluxio:2.9.0-SNAPSHOT](https://hub.docker.com/layers/alluxio/alluxio/alluxio/2.9.0-SNAPSHOT/images/sha256-e04e8a2ee017fd3d0af2e1924f2a9a720881d2b99000f3c189c49af8707473d5?context=explore)` image, and set `mountInPod` in your storageclass/pv to `true`. The fuse processes will be isolated into respective pods in this mode, and may solve the issue.

**Comment by lmssy** [comment]
@ssz1997 I have been set jvm stack size to 40M but stackoverflow is still there.
 About “set mountInPod in your storageclass/pv to true”， would you provide an example where to add this parameter？
Thansk a lot

**Comment by ssz1997** [comment]
@lmssy Only the alluxio snapshot image supports this functionality. 
If you are using helm chart, the version of the helm-chart should be at least 0.41. You can then set .csi.mountInPod to `true` in your config file.
If you are using yaml files:
If using pv, you can add `mountInPod: "true"` under `.spec.csi.volumeAtributes`, so it would look something like 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alluxio-pv
  labels:
    name: alluxio-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: alluxio
    volumeHandle: alluxio
    volumeAttributes:
      alluxioPath: /
      mountInPod: "false"
      javaOptions: -Dalluxio.user.metadata.cache.enabled=true 
  mountOptions:
  - "kernel_cache"
  - "allow_other"
  - "entry_timeout=36000"
  - "attr_timeout=36000"
  - "max_readahead=0"
```
For storage class, you can add `mountInPod: "true"` in `parameters`, and it would look something like:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alluxio
provisioner: alluxio
parameters:
  alluxioPath: /
  mountInPod: "false"
  javaOptions: -Dalluxio.user.metadata.cache.enabled=true 
volumeBindingMode: Immediate
mountOptions:
  - "kernel_cache"
  - "allow_other"
  - "entry_timeout=36000"
  - "attr_timeout=36000"
  - "max_readahead=0"
 ```
