### ISSUE TITLE
"I/O error" exception occurs when using deployment to create a lot of pods for alluxio-fuse

### ISSUE THREAD

**Issue by Haoning-Sun** [Alluxio/alluxio#15679]
**Alluxio Version:**
master.

**Describe the bug**

The log shows that the mount is successful, but the operation is abnormal and there is no log output. And this problem occurs with JNI-Fuse, but not with JNR-FUSE.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/13930429/172522681-fb2ff722-aedd-417e-9090-84525bc51525.png">

**To Reproduce**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-alluxio-sidecar
  labels:
    app: alluxio-sidecar
spec:
  replicas: 100
  selector:
    matchLabels:
      app: alluxio
      component: sidecar-example
  template:
    metadata:
      labels:
        app: alluxio
        component: sidecar-example
    spec:
      containers:
      - name: biz
        image: nginx
        volumeMounts:
        - mountPath: /mnt
          mountPropagation: HostToContainer
          name: alluxio-volume
      - name: alluxio-fuse
        lifecycle:
          preStop:
            exec:
              command:
              - integration/fuse/bin/alluxio-fuse
              - umount
              - /mnt/data
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: ["SYS_ADMIN"]
        image: alluxio/alluxio
        command: ["/bin/sh","-c"]
        args: ["integration/fuse/bin/alluxio-fuse mount -o allow_other /mnt/data /;while true; do date; sleep 5; done"]
        envFrom:
        - configMapRef:
            name: alluxio-config
        volumeMounts:
        - mountPath: /mnt
          name: alluxio-volume
          mountPropagation: Bidirectional
      volumes:
      - emptyDir: {}
        name: alluxio-volume
```

**Expected behavior**
After the mount is successful, the file can be accessed normally.
