### ISSUE TITLE
I use fuild + alluxio to cache cephfs but i seem to slow to cache so slowly.

### ISSUE THREAD

**Issue by andyzheung** [Alluxio/alluxio#16769]
**Alluxio Version:**
What version of Alluxio are you using?

**Describe the bug**
It takes about 10hours but only cache 40G data.

**To Reproduce**
fluid+alluixo 
2 GPU Server

**Expected behavior**
alluxio can cache data more quilcy

**Additional context**
log is here:
[alluxio logs.zip](https://github.com/Alluxio/alluxio/files/10417182/alluxio.logs.zip)

**Comment by ssz1997** [comment]
Configurations being used:

```
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: dataset-dev-k8s-cephfs
  namespace: liting
spec:
  replicas: 2
  properties:
    alluxio.underfs.cephfs.conf.file: /mnt/config/conf.file
    alluxio.underfs.cephfs.mds.namespace: cephfs
    alluxio.underfs.cephfs.mount.point: /autelrobotics/kubernetes/kubernetes/kubernetes-dynamic-pvc-84e94e3c-87e5-11ed-9e6d-263b1663e155
    alluxio.underfs.cephfs.auth.id: admin
    alluxio.underfs.cephfs.auth.keyring: /mnt/config/auth.keyring
    alluxio.user.file.passive.cache.enabled: "false"
    alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    alluxio.user.file.readtype.default: CACHE
    alluxio.user.block.avoid.eviction.policy.reserved.size.bytes: 209715MB
    alluxio.user.metadata.cache.enabled: "true"
    alluxio.user.metadata.cache.max.size: "50000000"
    alluxio.user.metadata.cache.expiration.time: 10min
    alluxio.user.worker.list.refresh.interval: 5min
    alluxio.user.rpc.retry.base.sleep: 200ms
    alluxio.user.file.metadata.sync.interval: 10min
    alluxio.master.ufs.active.sync.interval: 5min
  master:
    properties:
      alluxio.master.audit.logging.enabled: "false"
    jvmOptions: 
      - "-Xms128G"
      - "-Xmx128G"
    volumeMounts:
      - name: ceph-config
        mountPath: "/mnt/config"   # ConfigMap中的数据在容器中的挂载路径
        readOnly: true         # 必须为只读卷
  worker:
    jvmOptions:
      - "-Xms128G"
      - "-Xmx128G"
    volumeMounts:
      - name: ceph-config
        mountPath: "/mnt/config"   # ConfigMap中的数据在容器中的挂载路径
        readOnly: true         # 必须为只读卷
  jobMaster:
    volumeMounts:
      - name: ceph-config
        mountPath: "/mnt/config"   # ConfigMap中的数据在容器中的挂载路径
        readOnly: true         # 必须为只读卷
  jobWorker:
    volumeMounts:
      - name: ceph-config
        mountPath: "/mnt/config"   # ConfigMap中的数据在容器中的挂载路径
        readOnly: true         # 必须为只读卷
  volumes:
     # 通过挂载类型为configMap的只读卷来引用ConfigMap中的数据
    - name: ceph-config
      configMap:
        name: autonomy-dev-k8s-cephfs     # 要获取数据来源的ConfigMap名称
        # 来自ConfigMap的一组键，将被创建为文件
        items:
        - key: "auth.keyring"     # 需要从ConfigMap中取值的键
          path: "auth.keyring"    # 在volumeMounts.mountPath下挂载的路径名
        - key: "conf.file"
          path: "conf.file"
  tieredstore:
    levels:
      - path: /dev/shm
        mediumtype: MEM
        quota: 200Gi
      - path: /mnt/data01,/mnt/data02
        mediumtype: SSD
        quota: 6000Gi
```
