### ISSUE TITLE
extraVolumes dont work using Alluxio helm installation

### ISSUE THREAD

**Issue by loresding** [Alluxio/alluxio#17438]
**Alluxio Version:**
2.9.3

**Describe the bug**
I mount a volume to the worker container like this
```
extraVolumeMounts:
    - name: test
      path: <a path on worker container>
extraVolumes:
    - name: test
      path: <a path on your host machine>
      type: Directory
```
but it don't work, the worker contianer finally mount a emptyDir like this
 ```
volumes:
-  emptyDir: {}
    name: test
```
