### ISSUE TITLE
Why need to set `hostPID: true` in kubernetes/alluxio-master.yaml.template

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9018]
**Alluxio Version:**

v2.0.0-preview

**Describe the bug**
It's just a question. Why need to set `hostPID: true` in [kubernetes/alluxio-master.yaml.template](https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/alluxio-master.yaml.template#L56) ? 

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
@madanadit , can you help answering this question?

**Comment by madanadit** [comment]
Hi @cheyang, good catch. `hostPID` should not be required.

**Comment by madanadit** [comment]
https://github.com/Alluxio/alluxio/pull/9133

**Comment by madanadit** [comment]
Fix: https://github.com/Alluxio/alluxio/pull/9133

**Comment by MATRIX4284** [comment]
If Host PID is set to false Alluxio is Starting the master process with the master service defined in MASTER_HOSTNAME but Worker node is not able to resolve the worker service at port 29999.
Alluxio is failing to run in POD network only runs in host network.

**Comment by madanadit** [comment]
@MATRIX4284 this issue was talking about hostPID but not hostNetwork.

for your issue, this might help. we have updated the worker spec so that worker hostName is the physical IP of the host. this is resolvable from other containers which are not using host networking.

```
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: ALLUXIO_WORKER_JAVA_OPTS
            value: -Dalluxio.worker.hostname=$(ALLUXIO_WORKER_HOSTNAME)
```

let us know how it goes.
